include::ROOT:conf/Configuration_properties.adoc[leveloffset=0]

= Migration/Upgrade procedure

This section details the upgrade scenarios for {app-short-name} (Multi Operator Portal)
and Altiplano (AP), as well as how data integrity is managed during migration.

== Upgrade Scenarios

There are three main cases for upgrading {app-short-name} and the access platform components (Altiplano/AAC).
The process is defined based on which components require the update:

[width="99%",cols="40%,59%,options="header"]
|===
|*Scenario*|*Procedure*
|Upgrade {app-short-name} only| Direct upgrade of the {app-short-name} platform is performed.
|Upgrade Altiplano/AAC only|{app-short-name} must be redeployed only if Altiplano's certificates change after the upgrade.
Additionally, Keycloak secrets must be reconfigured on {app-short-name} if the {app-short-name} Keycloak secrets have changed.
|Upgrade {app-short-name} and Altiplano/AAC|- Step 1: Upgrade the AAC (Altiplano Access Controller).

- Step 2: Upgrade {app-short-name}.
|===

=== Compatibility and Timing Considerations
- Compatibility: Please check the xref:Solution_planning_guidelines_for_WNP_application.adoc#_compatibility[{app-short-name} Compatibility] section.
Upgrades of {app-short-name} and/or Altiplano must remain within this AAC compatibility range.
- Maintenance Window: The {app-short-name} upgrade is done typically in the order of minutes (around 5 minutes).
This makes it possible to sequentially upgrade AAC first, then {app-short-name}, within the same maintenance window.

[NOTE]
====
If the intent type versions are changed, {app-short-name} configuration needs to be reviewed in order to adjust the "intent type version" and "intent type default version" configuration for each ISP.
====

include::ROOT:go-back-component.adoc[Back]