include::ROOT:conf/Configuration_properties.adoc[leveloffset=0]

= What's new in Release 26.3

This is the initial release of the Multi Operator Portal, intended for the Nokia team to perform internal installation and testing.
The application includes all WNP functionalities while also enabling the management of intent types across the entire OLT stack.
The two key features added to this version, available for all intent types, are:

* Support for the following intent types:
- device-xx (Where “xx” can be “mf”, “fx”, “sf”, or “df”)
- device-config-xx (Where “xx” can be “mf”, “fx”, “sf”, or “df”)
- ont
- uplink-connection
- fiber
- l2-infra
- mcast-infra
- l3-infra
- l2-mgmt-infra
- l2-user
- mcast-user
- standard-voip-sip-user
- cfm
- ethernet-ring-infra
- standard-voip-sip-agent

* Support for alarms and metrics across all OLT elements. (Through kafka, Opensearch and OpenTSDB)

[IMPORTANT]
====
In this initial version, the application's interface remains similar to the Wholesale Network Portal.
However, it differs by enabling the manipulation and configuration of all intents within the OLT stack via the VNO UI and the IBN proxy. Moving forward, the product will be adapted to feature a distinct look and feel if required by Nokia's specific needs.
====

include::ROOT:go-back-component.adoc[Back]