include::ROOT:conf/Configuration_properties.adoc[leveloffset=0]

= How to Use {app-short-name} as {inp-initials}

This section provides the steps needed to configure the application.

When the {app-short-name} is installed on top of an {main-base-app} solution, the {inp-initials} user must set up the {vno-initials}s and configure the rules to define the restrictions each {vno-initials} has to interact with {main-base-app} interfaces.
The {app-short-name} allows to configure global rules applying to all the {vno-initials}s and also rules applying only to a specific {vno-initials}.
Please refer to Wholesale Network Portal doc to know how to configure MOP application.
This is the initial release of the Multi Operator Portal, intended for the Nokia team to perform internal installation and testing.
The application includes all WNP functionalities while also enabling the management of intent types across the entire OLT stack.
The only feature that is disabled for {app-short-name} is the Assigned resources feature of WNP because in {app-short-name}
the ISP owned the full OLT.



include::ROOT:go-back-component.adoc[Back]