include::ROOT:conf/Configuration_properties.adoc[leveloffset=0]

= {app-short-name} Features

== ONU Activation

This feature consists of checking different actions over ONTs that must be allowed or denied for {vno-initials}s.
5 different options are available to be configured depending if is an {inp-initials} or {vno-initials}:

- *None*: Select this option when no ONU Activation option should be applied. The {vno-initials} can execute any operation and changes over the ONT intents.
- *Inherited*: To inherit the onu activation option set as global rule to all the {vno-initials}s. This option is only available for an {vno-initials} user.
- *By {vno-initials}*: Select this option when the {vno-initials} is in charge of creating/deleting the ONT intent, but the {inp-initials} is in charge of the first synchronization attempt. The {vno-initials} is allowed to execute any operation and change any field of ont intents, except for the first synchronization.
- *By {vno-initials} on {inp-initials} Provided ONT*: Select this option when the {inp-initials} is in charge of creating/deleting the ONT intent
and the {vno-initials} can update attributes and synchronize. The {vno-initials} is not able to create, delete ONT intents, or change the pon port (fiber).
It is only allowed to modify all the other ONT information and synchronize.
- *By {inp-initials}*: Select this option when the {inp-initials} is in charge of creating/deleting the ONT intent (assigning the identifier attributes)
and the {vno-initials} is only allowed to change non identifier attributes and synchronize. The {vno-initials} is not able to create, delete ONT intents, change the pon port (fiber), serial number or registration ID. It is only allowed to modify all the other ONT information and synchronize.

When an {vno-initials} sends an ont intent request to {main-base-app} through the {app-short-name},
the application checks the configured option to reject or allowed the action.

[width="100%",cols="40%,15%,15%,15%,15%",options="header"]
|===
|*Actions allowed to ISP* |*ByINP* |*ByISPonINPprovidedONT* |*ByISP* |*None*
|Create/Delete ONT|No|No|Yes|Yes
|First sync|Yes|Yes|No|Yes
|Edit Fiber info|No|No|Yes|Yes
|Edit SN / RegID|No|Yes|Yes|Yes
|Edit other ONT config *|Yes|Yes|Yes|Yes
|===

&#42; Following Altiplano configuration change restrictions.

== Allowed Intent Types

//TODO: (lea) COMPLETAR FEATURE!

{app-short-name} is capable of allowing specific intent types and versions.

{app-short-name} can allow/deny specific intent types and versions to specific {vno-initials}s.

When an {vno-initials} sends an intent request to {main-base-app} through the {app-short-name}, the application checks if the intent type and version of the request is configured in the allowed list.

== Intent Type Allowed Actions

//TODO: (lea) COMPLETAR FEATURE!

{app-short-name} is capable of allowing specific actions that can be executed over the intent types.

When an {vno-initials} sends an action request to {main-base-app} through the {app-short-name}, the application checks if the action is configured for the intent type in the allowed action list.

== Default Versions

//TODO: (lea) COMPLETAR FEATURE!

{app-short-name} can manage default intent type versions.
When an {vno-initials} sends an intent request to {main-base-app} through the {app-short-name},
the application verifies if the request contains a version in the intent-type-version attribute.
If it is not present and {app-short-name} has configured a default version,
then it is added to the intent before sending to {main-base-app}.

== Data Constraints

//TODO: (lea) COMPLETAR FEATURE!

{app-short-name} can be configured to add extra constraint checks at the level of intent attributes.
When an {vno-initials} sends an intent request to {main-base-app} through the {app-short-name},
the application inspects the intent attributes and check if there is any constraint configured for them.
If there are configured constraints for intent attributes, then the {app-short-name}
checks that the values are allowed.

There are various types of restrictions allowed: List, ProfileList, Regexp and Range.

== Intent Input Injections

//TODO: (lea) REVISAR FEATURE!

{app-short-name} can be configured to add fixed values to intent fields and to hide fields of intent to the {vno-initials}s.

When an {vno-initials} sends an intent request to {main-base-app} through the {app-short-name},
the application checks {vno-initials}'s Intent Input Injections configuration and adds the configured values
for each configured intent field.

Also the metadata yang model of the intents is filtered by {app-short-name} removing
the intent fields that are configured as "hide to {vno-initials}". The {vno-initials} does not
know about that hidden fields.

== Readable Intent Types

//TODO: (lea) REVISAR FEATURE!
{app-short-name} can be configured to add readable intent types.

An {vno-initials} uses these intent types for doing queries from OpenSearch.

== Allowed Intent Attributes

//TODO: (lea) REVISAR FEATURE!
For each readable intent type, you can configure the allowed intent attributes, which are the fields retrieved from OpenSearch when {vno-initials}s access the intents information.

== Blocked Alarm Types

//TODO: (lea) ESCRIBIR FEATURE!
{app-short-name} can be configured to block alarms of specific alarm types.

When an {vno-initials} sends an alarm request to {main-base-app} through the {app-short-name}, the application gets the blocked alarm types configuration and filters the request returning to the {vno-initials} only the alarms that contains allowed alarm types .

== SNMP Trap Destinations

//TODO: (lea) REVISAR FEATURE!
WNP can be configured to send the filtered alarms notifications via SNMP Traps.

When {main-base-app} sends alarm notifications to {app-short-name}, the {app-short-name} filters the alarms to be sent to Kafka and by SNMP Traps.

== Assigned Network Resources

//TODO: (lea) REVISAR FEATURE!
{app-short-name} can be configured to assign network resources to an {vno-initials}.

An {vno-initials} only creates intents of the intent types that were assigned like network resources.

Then these assignments can be used to filter intents, offer an intent summary, filter the Metrics/Alarms data and also to translate the {vno-initials} names to
the {main-base-app} intent target per {vno-initials} if a different name was present in the assignments file.

[id=assigned_network_resources_file_format]
JSON configuration file format::
The JSON file format must adhere to the following format:
+
[source, json]
----
{
    "assigned-network-resources": [
        {
            "device-id": <DEVICE_TARGET1>,
            "alias": <DEVICE_ALIAS1>
        },
        {
            "device-id": <DEVICE_TARGET2>   //In this case, the OLT has not an assigned alias
        },
        {
            "fiber-id": <FIBER_TARGET1>,
            "alias": <FIBER_ALIAS1>
        },
        {
            "fiber-id": <FIBER_TARGET2>   //In this case, the PON port has not an assigned alias
        },
        {
            "pon-id-matching-pattern": <REGULAR_EXPRESSION>,
            "pon-id-matching-alias": <ALIAS_REGULAR_EXPRESSION>
        }
    ]
}
----
- *assigned-network-resources*: The list of devices and PON ports to assign.
* *device-id*(device target): In case it is present, it refers to the target of the device-xx intent used in {main-base-app}.
* *fiber-id*(fiber target): In case it is present, it is the target of the fiber intent used in {main-base-app}.
* *alias (optional)*: It is the device or fiber's assigned alias in {app-short-name}. Refer to  xref:#_aliases_for_assigned_resources[Aliases for Assigned Resources] section.
* *pon-id-matching-pattern*: In case it is present, it supports the assignment using the pon id syntax of the fiber intent.
This allows the use of regular expressions to assign multiple fibers at once.
<REGULAR_EXPRESSION> must be formed as <DEVICE_TARGET>.<LT_BOARD>.<PON_NUMBER>. The regexp only accepts physical identifiers, does not accept alias as identifiers.
* *pon-id-matching-alias*: It is the attribute that defines the format to dynamically build aliases used by the {vno-initials} for the pon-id-matching-pattern matched elements. +
<REGULAR_EXPRESSION> must be formed as:
** <DEVICE_TARGET> Refers to the OLT target (optional)
** <DEVICE_ALIAS> Refers to the OLT alias previously assigned. If no alias is assigned an error will be informed and the alias won’t be applied. (optional)
** <LT_NUMBER> Refers to the LT Board number (mandatory)
** <PON_NUMBER> Refers to the PON Port number (mandatory)
//TODO: (lea) VERIFICAR EL CORRECTO USO DE LA REGULAR EXPRESSION EN LOS EJEMPLOS DADOS!
+
[NOTE]
====
Device target is the OLT's target and Fiber target is the PON port's target.
====
+
*Regexp Examples of pon-id-matching-pattern:*
+
*** *"Condor-LS.LT[1-2].+++PON*+++"*: Regexp for assigning all resources (Devices, LT boards and PON ports) that belong to "Condor-LS" OLT and LT 1 and LT 2.
*** *"Condor-LS.LT3.PON3"*: Regexp for assigning the PON port 3 that belong to "Condor-LS" OLT and LT 3.
+
For example:: If the {inp-initials} wants to assign resources with some aliases to {vno-initials} two OLTs whose targets are "Condor-LS" and Test-OLT"
and two PON ports whose targets are "Condor-LS.L1.P1" and "Condor-LS.L1.P2", the following JSON must be loaded:
+
[source, json]
----
{
        "assigned-network-resources": [
            {
                "device-id": "Condor-LS",
                "alias": "OLT1"
            },
            {
                "device-id": "Test-OLT"
            },
            {
                "fiber-id": "Condor-LS.L1.P1"
            },
            {
                "fiber-id": "Condor-LS.L1.P2",
                "alias": "OLT1.Fiber2"
            },
            {
                "pon-id-matching-pattern": "Condor-LS.LT[3-6].PON*",
                "pon-id-matching-alias": "Test(<DEVICE_TARGET>)-<LT_NUMBER>.<PON_NUMBER>Alias"
            }
        ]
}
----
+
For example:: If the {inp-initials} wants to assign to {vno-initials} all PON ports of an OLT whose target is "Condor-LS",
the following JSON must be loaded:
+
[source, json]
----
{
        "assigned-network-resources": [
            {
                "pon-id-matching-pattern": "Condor-LS.LT*.PON*"
            }
        ]
}
----
+
For example:: If the {inp-initials} wants to assign to {vno-initials}, the OLT whose target is "Condor-XS" and
all LT1 and LT2 boards' PON ports of an OLT whose target is "Condor-LS", the following JSON must be loaded:
+
[source, json]
----
{
        "assigned-network-resources": [
            {
                "device-id": "Condor-XS"
            },
            {
                "pon-id-matching-pattern": "Condor-LS.LT[1-2].PON*"
            }
        ]
}
----


[IMPORTANT]
====
Each time new fibers/OLTs need to be assigned, the whole updated file must be uploaded.
{app-short-name} will compare the assigned elements in DB to know which elements to delete (not present in the new file and present in the DB)
and which elements to create (elements present in the new file and not in DB).
====

For example:: If the {inp-initials} wants to delete all assigned network resources of an {vno-initials}, the following JSON must be loaded:
+
[id=desassign_all_assigned_network_resources_file_format]
[source, json]
----
{
        "assigned-network-resources": [
        ]
}
----

== Aliases for Assigned Resources

//TODO: (lea) REVISAR FEATURE!
{app-short-name} can be configured to assign identifiers to network resources of the {vno-initials}s.

An {vno-initials} can assign a unique alias per device/fiber. Each alias must be unique per {vno-initials}.

These identifiers are the ones used by the {vno-initials}, so sometimes it does not match the name on {main-base-app} of the resources.
This will be treated as an alias for the real name of the device/fiber element.

The {vno-initials} will be only capable of acting over the resources that were assigned to it.
For more detail of this feature, refer to xref:appendices/features.adoc#_assigned_network_resources[Assigned Network Resources] section.

== Live Collections

{app-short-name} can be configured to control the live collections execution.

When an {vno-initials} starts a live collection to {main-base-app} through the {wnp-ibn-context}, {app-short-name} checks the duration and the period configured for the {vno-initials} and is in charge of injecting the configured periodicity, the start time and the stop time for the {vno-initials} that is sending the request before forwarding it to {main-base-app}.

Also {wnp-ibn-context} controls the maximum number of simultaneous live collections per {vno-initials} that can be executed according to the {app-short-name} configuration.
This live collection will also be allowed to be executed using the Web UI.

{vno-initials} will be able to execute live collection over the owned intents (ont and services) and also over the assigned network resources if the feature is enabled(device-xx and fiber intents).
For more detail of this feature, refer to xref:appendices/features.adoc#_assigned_network_resources[Assigned Network Resources] section.

Note: an {inp-initials} user will be able to execute any live collection.

== Software Management

{app-short-name} can be configured to enable or disable Software Management access for {vno-initials}s.

An {vno-initials} can manage Target Solutions and Campaigns through both the REST API or the Web UI.

An {inp-initials} only can manage the campaigns via Web UI, utilizing a calendar view to monitor the campaigns created by the {vno-initials}s.

